automotive_and_vehicles = [
    {"id": 21, "name": "Cars", "is_root": False, "parents": [1], "properties": [
        ("make", str),
        ("model", str),
        ("year", int),
        ("mileage_km", int),
        ("fuel_type", str, ["Petrol", "Diesel", "Electric", "Hybrid", "CNG", "LPG", "Other"]),
        ("transmission", str, ["Manual", "Automatic", "CVT", "Semi-Automatic", "Dual-Clutch", "Other"]),
        ("body_type", str, ["Sedan", "Hatchback", "SUV", "Coupe", "Convertible", "Wagon", "Van", "Pickup Truck", "Minivan", "Other"]),
        ("drivetrain", str, ["FWD", "RWD", "AWD", "4WD", "Other"]),
        ("number_of_doors", int),
        ("number_of_seats", int),
        ("engine_size_cc", int),
        ("horsepower_hp", int),
        ("torque_nm", int),
        ("fuel_consumption_l_per_100km", float),
    ]},

    {"id": 22, "name": "New Cars", "is_root": False, "parents": [21], "properties": [
        ("make", str),
        ("model", str),
        ("year", int),
        ("fuel_type", str, ["Petrol", "Diesel", "Electric", "Hybrid", "CNG", "LPG", "Other"]),
        ("transmission", str, ["Manual", "Automatic", "CVT", "Semi-Automatic", "Dual-Clutch", "Other"]),
        ("body_type", str, ["Sedan", "Hatchback", "SUV", "Coupe", "Convertible", "Wagon", "Van", "Pickup Truck", "Minivan", "Other"]),
        ("drivetrain", str, ["FWD", "RWD", "AWD", "4WD", "Other"]),
        ("number_of_doors", int),
        ("number_of_seats", int),
        ("engine_size_cc", int),
        ("horsepower_hp", int),
        ("torque_nm", int),
        ("fuel_consumption_l_per_100km", float),
        ("warranty_years", int),
        ("delivery_time_days", int),
    ]},

    {"id": 23, "name": "Used Cars", "is_root": False, "parents": [21], "properties": [
        ("make", str),
        ("model", str),
        ("year", int),
        ("mileage_km", int),
        ("fuel_type", str, ["Petrol", "Diesel", "Electric", "Hybrid", "CNG", "LPG", "Other"]),
        ("transmission", str, ["Manual", "Automatic", "CVT", "Semi-Automatic", "Dual-Clutch", "Other"]),
        ("body_type", str, ["Sedan", "Hatchback", "SUV", "Coupe", "Convertible", "Wagon", "Van", "Pickup Truck", "Minivan", "Other"]),
        ("drivetrain", str, ["FWD", "RWD", "AWD", "4WD", "Other"]),
        ("number_of_doors", int),
        ("number_of_seats", int),
        ("engine_size_cc", int),
        ("horsepower_hp", int),
        ("torque_nm", int),
        ("fuel_consumption_l_per_100km", float),
        ("number_of_previous_owners", int),
        ("accident_history", bool),
        ("service_history_available", bool),
    ]},

    {"id": 24, "name": "Motorcycles", "is_root": False, "parents": [1], "properties": [
        ("make", str),
        ("model", str),
        ("year", int),
        ("mileage_km", int),
        ("engine_size_cc", int),
        ("engine_type", str, ["Single-cylinder", "Parallel Twin", "V-Twin", "Inline-3", "Inline-4", "V4", "Electric", "Other"]),
        ("fuel_type", str, ["Petrol", "Electric", "Other"]),
        ("transmission", str, ["Manual", "Automatic"]),
        ("type", str, ["Cruiser", "Sport", "Touring", "Standard", "Dual-Sport", "Scooter", "Off-Road", "Other"]),
        ("number_of_cylinders", int),
    ]},

    {"id": 25, "name": "Trucks & Vans", "is_root": False, "parents": [1], "properties": [
        ("make", str),
        ("model", str),
        ("year", int),
        ("mileage_km", int),
        ("fuel_type", str, ["Petrol", "Diesel", "Electric", "Hybrid", "CNG", "LPG", "Other"]),
        ("transmission", str, ["Manual", "Automatic", "CVT", "Semi-Automatic", "Dual-Clutch", "Other"]),
        ("body_type", str, ["Pickup Truck", "Van", "Minivan", "Cargo Van", "Passenger Van", "Box Truck", "Other"]),
        ("drivetrain", str, ["FWD", "RWD", "AWD", "4WD", "Other"]),
        ("number_of_doors", int),
        ("number_of_seats", int),
        ("engine_size_cc", int),
        ("horsepower_hp", int),
        ("torque_nm", int),
        ("payload_capacity_kg", int),
        ("towing_capacity_kg", int),
        ("bed_length_ft", float),
        ("fuel_consumption_l_per_100km", float),
    ]},

    {"id": 26, "name": "Recreational Vehicles (RVs)", "is_root": False, "parents": [1], "properties": [
        ("make", str),
        ("model", str),
        ("year", int),
        ("mileage_km", int),
        ("type", str, ["Class A", "Class B", "Class C", "Travel Trailer", "Fifth Wheel", "Toy Hauler", "Pop-up Camper", "Truck Camper", "Other"]),
        ("fuel_type", str, ["Petrol", "Diesel", "Electric", "Other"]),
        ("length_ft", float),
        ("number_of_sleeping_areas", int),
        ("number_of_slideouts", int),
        ("air_conditioning", bool),
        ("generator_included", bool),
    ]},

    {"id": 27, "name": "Boats & Watercraft", "is_root": False, "parents": [1], "properties": [
        ("make", str),
        ("model", str),
        ("year", int),
        ("length_ft", float),
        ("type", str, ["Sailboat", "Motorboat", "Yacht", "Jet Ski", "Kayak", "Canoe", "Fishing Boat", "Pontoon Boat", "Other"]),
        ("fuel_type", str, ["Petrol", "Diesel", "Electric", "Human-Powered", "Other"]),
        ("engine_hours", int),
        ("number_of_engines", int),
        ("engine_power_hp", int),
        ("hull_material", str, ["Fiberglass", "Aluminum", "Wood", "Steel", "Other"]),
    ]},

    {"id": 28, "name": "Vehicle Parts & Accessories", "is_root": False, "parents": [1], "properties": []},

    {"id": 29, "name": "Car Parts", "is_root": False, "parents": [28], "properties": [
        ("part_type", str, ["Engine", "Transmission", "Brakes", "Suspension", "Exhaust", "Body", "Electrical", "Cooling System", "Fuel System", "Steering", "Interior", "Other"]),
        ("compatible_make", str),
        ("compatible_model", str),
        ("compatible_years", str),
        ("part_number", str),
        ("oem_or_aftermarket", str, ["OEM", "Aftermarket"]),
        ("warranty_months", int),
    ]},

    {"id": 30, "name": "Motorcycle Parts", "is_root": False, "parents": [28], "properties": [
        ("part_type", str, ["Engine", "Transmission", "Brakes", "Suspension", "Exhaust", "Body", "Electrical", "Cooling System", "Fuel System", "Steering", "Other"]),
        ("compatible_make", str),
        ("compatible_model", str),
        ("compatible_years", str),
        ("part_number", str),
        ("oem_or_aftermarket", str, ["OEM", "Aftermarket"]),
        ("warranty_months", int),
    ]},

    {"id": 31, "name": "Tires & Wheels", "is_root": False, "parents": [28], "properties": [
        ("type", str, ["Tire", "Wheel", "Tire & Wheel Package", "Other"]),
        ("tire_size", str),
        ("wheel_size_inches", int),
        ("bolt_pattern", str),
        ("offset_mm", int),
        ("tire_type", str, ["All-Season", "Summer", "Winter", "All-Terrain", "Performance", "Other"]),
        ("brand", str),
        ("model", str),
        ("load_index", int),
        ("speed_rating", str),
    ]},

    {"id": 32, "name": "Vehicle Electronics", "is_root": False, "parents": [28], "properties": [
        ("type", str, ["Car Audio", "Navigation System", "Backup Camera", "Dash Cam", "Alarm System", "Remote Start", "OBD-II Scanner", "Other"]),
        ("brand", str),
        ("model", str),
        ("compatible_vehicles", str),
        ("features", str),
    ]},

    {"id": 33, "name": "Exterior Accessories", "is_root": False, "parents": [28], "properties": [
        ("type", str, ["Roof Rack", "Bike Rack", "Spoiler", "Body Kit", "Side Steps", "Mud Flaps", "Grille Guard", "Other"]),
        ("compatible_make", str),
        ("compatible_model", str),
        ("compatible_years", str),
        ("material", str, ["Steel", "Aluminum", "Plastic", "Composite", "Other"]),
        ("color", str),
    ]},

    {"id": 34, "name": "Interior Accessories", "is_root": False, "parents": [28], "properties": [
        ("type", str, ["Seat Covers", "Floor Mats", "Steering Wheel Cover", "Shift Knob", "Dashboard Cover", "Organizers", "Other"]),
        ("compatible_make", str),
        ("compatible_model", str),
        ("compatible_years", str),
        ("material", str, ["Leather", "Fabric", "Rubber", "Plastic", "Other"]),
        ("color", str),
    ]},

    {"id": 35, "name": "Other Vehicles", "is_root": False, "parents": [1], "properties": []},

    {"id": 36, "name": "Bicycles", "is_root": False, "parents": [35], "properties": [
        ("brand", str),
        ("model", str),
        ("type", str, ["Road Bike", "Mountain Bike", "Hybrid Bike", "BMX", "Folding Bike", "Electric Bike", "Other"]),
        ("frame_material", str, ["Aluminum", "Carbon Fiber", "Steel", "Titanium", "Other"]),
        ("wheel_size_inches", int),
        ("number_of_gears", int),
        ("brake_type", str, ["Disc", "Rim", "Drum", "Other"]),
        ("suspension", str, ["None", "Front Suspension", "Full Suspension"]),
        ("motor_power_watts", int),  # For electric bikes
        ("battery_capacity_ah", float),  # For electric bikes
    ]},

    {"id": 37, "name": "ATVs & UTVs", "is_root": False, "parents": [35], "properties": [
        ("type", str, ["ATV", "UTV", "Side-by-Side", "Other"]),
        ("make", str),
        ("model", str),
        ("year", int),
        ("engine_size_cc", int),
        ("drive_type", str, ["2WD", "4WD", "Other"]),
        ("fuel_type", str, ["Petrol", "Diesel", "Electric", "Other"]),
        ("mileage_km", int),
    ]},
]
