books_movies_music = [
    # Books, Movies & Music
    {"id": 257, "name": "Books", "is_root": False, "parents": [6], "properties": [
        ("title", str),
        ("author", str),
        ("genre", str),
        ("format", str, ["Hardcover", "Paperback", "eBook", "Audiobook"]),
        ("language", str),
        ("publication_year", int),
        ("publisher", str),
        ("isbn", str),
        ("number_of_pages", int),
        ("series", str),
        ("edition", str),
    ]},

    {"id": 258, "name": "Fiction", "is_root": False, "parents": [257], "properties": [
        ("title", str),
        ("author", str),
        ("subgenre", str, ["Fantasy", "Science Fiction", "Romance", "Thriller", "Mystery", "Historical Fiction", "Young Adult", "Children's", "Horror", "Literary Fiction", "Other"]),
        ("format", str, ["Hardcover", "Paperback", "eBook", "Audiobook"]),
        ("language", str),
        ("publication_year", int),
        ("publisher", str),
        ("isbn", str),
        ("number_of_pages", int),
        ("series", str),
        ("edition", str),
    ]},

    {"id": 259, "name": "Non-Fiction", "is_root": False, "parents": [257], "properties": [
        ("title", str),
        ("author", str),
        ("subgenre", str, ["Biography", "Memoir", "Self-Help", "History", "Science", "Philosophy", "Business", "Travel", "Cooking", "Art", "Other"]),
        ("format", str, ["Hardcover", "Paperback", "eBook", "Audiobook"]),
        ("language", str),
        ("publication_year", int),
        ("publisher", str),
        ("isbn", str),
        ("number_of_pages", int),
        ("series", str),
        ("edition", str),
    ]},

    {"id": 260, "name": "Children's Books", "is_root": False, "parents": [257], "properties": [
        ("title", str),
        ("author", str),
        ("age_group", str, ["Baby to 2", "Ages 3-5", "Ages 6-8", "Ages 9-12", "Teen & Young Adult"]),
        ("subgenre", str, ["Picture Books", "Early Learning", "Fairy Tales", "Action & Adventure", "Animals", "Other"]),
        ("format", str, ["Hardcover", "Paperback", "eBook", "Audiobook"]),
        ("language", str),
        ("publication_year", int),
        ("publisher", str),
        ("isbn", str),
        ("number_of_pages", int),
        ("series", str),
        ("edition", str),
    ]},

    {"id": 261, "name": "Educational & Textbooks", "is_root": False, "parents": [257], "properties": [
        ("title", str),
        ("author", str),
        ("subject", str, ["Mathematics", "Science", "History", "Literature", "Languages", "Engineering", "Medicine", "Law", "Business", "Social Sciences", "Other"]),
        ("academic_level", str, ["High School", "Undergraduate", "Graduate", "Professional", "Other"]),
        ("format", str, ["Hardcover", "Paperback", "eBook"]),
        ("language", str),
        ("publication_year", int),
        ("publisher", str),
        ("isbn", str),
        ("number_of_pages", int),
        ("edition", str),
        ("series", str),
    ]},

    {"id": 262, "name": "Comics & Graphic Novels", "is_root": False, "parents": [257], "properties": [
        ("title", str),
        ("author", str),
        ("illustrator", str),
        ("subgenre", str, ["Superhero", "Manga", "Science Fiction", "Fantasy", "Humor", "Horror", "Other"]),
        ("format", str, ["Paperback", "Hardcover", "Digital"]),
        ("language", str),
        ("publication_year", int),
        ("publisher", str),
        ("isbn", str),
        ("number_of_pages", int),
        ("series", str),
        ("volume", int),
        ("edition", str),
    ]},

    {"id": 263, "name": "Movies & TV Shows", "is_root": False, "parents": [6], "properties": [
        ("title", str),
        ("director", str),
        ("cast", str),
        ("genre", str, ["Action", "Comedy", "Drama", "Horror", "Thriller", "Romance", "Sci-Fi", "Fantasy", "Documentary", "Animation", "Family", "Other"]),
        ("format", str, ["DVD", "Blu-ray", "Digital", "VHS"]),
        ("release_year", int),
        ("language", str),
        ("runtime_minutes", int),
        ("rating", str, ["G", "PG", "PG-13", "R", "NC-17", "Not Rated"]),
        ("studio", str),
        ("number_of_discs", int),
        ("subtitle_languages", str),
    ]},

    {"id": 264, "name": "DVDs & Blu-rays", "is_root": False, "parents": [263], "properties": [
        ("title", str),
        ("director", str),
        ("cast", str),
        ("genre", str, ["Action", "Comedy", "Drama", "Horror", "Thriller", "Romance", "Sci-Fi", "Fantasy", "Documentary", "Animation", "Family", "Other"]),
        ("format", str, ["DVD", "Blu-ray", "4K Ultra HD"]),
        ("release_year", int),
        ("language", str),
        ("runtime_minutes", int),
        ("rating", str, ["G", "PG", "PG-13", "R", "NC-17", "Not Rated"]),
        ("studio", str),
        ("number_of_discs", int),
        ("region_code", str, ["Region Free", "Region 1", "Region 2", "Region 3", "Region 4", "Region 5", "Region 6", "Region A", "Region B", "Region C"]),
        ("subtitle_languages", str),
    ]},

    {"id": 265, "name": "Digital Downloads", "is_root": False, "parents": [263], "properties": [
        ("title", str),
        ("director", str),
        ("cast", str),
        ("genre", str, ["Action", "Comedy", "Drama", "Horror", "Thriller", "Romance", "Sci-Fi", "Fantasy", "Documentary", "Animation", "Family", "Other"]),
        ("format", str, ["Digital"]),
        ("release_year", int),
        ("language", str),
        ("runtime_minutes", int),
        ("rating", str, ["G", "PG", "PG-13", "R", "NC-17", "Not Rated"]),
        ("studio", str),
        ("digital_platform", str),
        ("file_size_mb", int),
        ("resolution", str, ["SD", "HD", "Full HD", "4K"]),
        ("subtitle_languages", str),
    ]},

    {"id": 425, "name": "Prime Video Streaming", "is_root": False, "parents": [263], "properties": [
        ("title", str),
        ("director", str),
        ("cast", str),
        ("genre", str, ["Action", "Comedy", "Drama", "Horror", "Thriller", "Romance", "Sci-Fi", "Fantasy", "Documentary", "Animation", "Family", "Other"]),
        ("format", str, ["Streaming"]),
        ("release_year", int),
        ("language", str),
        ("runtime_minutes", int),
        ("rating", str, ["G", "PG", "PG-13", "R", "NC-17", "Not Rated"]),
        ("studio", str),
        ("streaming_service", str, ["Amazon Prime Video"]),
        ("resolution", str, ["SD", "HD", "Full HD", "4K"]),
        ("subtitle_languages", str),
    ]},

    {"id": 266, "name": "VHS", "is_root": False, "parents": [263], "properties": [
        ("title", str),
        ("director", str),
        ("cast", str),
        ("genre", str, ["Action", "Comedy", "Drama", "Horror", "Thriller", "Romance", "Sci-Fi", "Fantasy", "Documentary", "Animation", "Family", "Other"]),
        ("format", str, ["VHS"]),
        ("release_year", int),
        ("language", str),
        ("runtime_minutes", int),
        ("rating", str, ["G", "PG", "PG-13", "R", "NC-17", "Not Rated"]),
        ("studio", str),
        ("subtitle_languages", str),
        ("tape_length_minutes", int),
    ]},

    {"id": 267, "name": "Music", "is_root": False, "parents": [6], "properties": [
        ("title", str),
        ("artist", str),
        ("genre", str, ["Rock", "Pop", "Hip Hop", "Jazz", "Classical", "Country", "Electronic", "R&B", "Reggae", "Blues", "Other"]),
        ("format", str, ["CD", "Vinyl", "Digital", "Cassette"]),
        ("release_year", int),
        ("label", str),
        ("number_of_tracks", int),
        ("language", str),
        ("duration_minutes", int),
        ("explicit_content", bool),
    ]},

    {"id": 268, "name": "CDs", "is_root": False, "parents": [267], "properties": [
        ("title", str),
        ("artist", str),
        ("genre", str, ["Rock", "Pop", "Hip Hop", "Jazz", "Classical", "Country", "Electronic", "R&B", "Reggae", "Blues", "Other"]),
        ("format", str, ["CD"]),
        ("release_year", int),
        ("label", str),
        ("number_of_tracks", int),
        ("number_of_discs", int),
        ("language", str),
        ("duration_minutes", int),
        ("explicit_content", bool),
    ]},

    {"id": 269, "name": "Vinyl Records", "is_root": False, "parents": [267], "properties": [
        ("title", str),
        ("artist", str),
        ("genre", str, ["Rock", "Pop", "Hip Hop", "Jazz", "Classical", "Country", "Electronic", "R&B", "Reggae", "Blues", "Other"]),
        ("format", str, ["Vinyl"]),
        ("release_year", int),
        ("label", str),
        ("number_of_tracks", int),
        ("number_of_discs", int),
        ("language", str),
        ("duration_minutes", int),
        ("speed_rpm", int, [33, 45, 78]),
        ("size_inches", int, [12, 7, 10]),
        ("explicit_content", bool),
    ]},

    {"id": 270, "name": "Digital Music", "is_root": False, "parents": [267], "properties": [
        ("title", str),
        ("artist", str),
        ("genre", str, ["Rock", "Pop", "Hip Hop", "Jazz", "Classical", "Country", "Electronic", "R&B", "Reggae", "Blues", "Other"]),
        ("format", str, ["Digital"]),
        ("release_year", int),
        ("label", str),
        ("number_of_tracks", int),
        ("language", str),
        ("duration_minutes", int),
        ("file_format", str, ["MP3", "FLAC", "AAC", "WAV", "Other"]),
        ("bitrate_kbps", int),
        ("explicit_content", bool),
    ]},

    {"id": 271, "name": "Video Games", "is_root": False, "parents": [6], "properties": [
        ("title", str),
        ("platform", str, ["PlayStation", "Xbox", "Nintendo Switch", "PC", "Mac", "Other"]),
        ("genre", str, ["Action", "Adventure", "RPG", "Simulation", "Strategy", "Sports", "Racing", "Puzzle", "Other"]),
        ("release_year", int),
        ("publisher", str),
        ("developer", str),
        ("age_rating", str, ["E", "E10+", "T", "M", "AO", "RP"]),
        ("single_player", bool),
        ("multi_player", bool),
        ("online_play", bool),
        ("physical_or_digital", str, ["Physical", "Digital"]),
    ]},

    {"id": 272, "name": "Games", "is_root": False, "parents": [271], "properties": [
        ("title", str),
        ("platform", str, ["PlayStation", "Xbox", "Nintendo Switch", "PC", "Mac", "Other"]),
        ("genre", str, ["Action", "Adventure", "RPG", "Simulation", "Strategy", "Sports", "Racing", "Puzzle", "Other"]),
        ("release_year", int),
        ("publisher", str),
        ("developer", str),
        ("age_rating", str, ["E", "E10+", "T", "M", "AO", "RP"]),
        ("single_player", bool),
        ("multi_player", bool),
        ("online_play", bool),
        ("physical_or_digital", str, ["Physical", "Digital"]),
    ]},

    {"id": 273, "name": "Accessories", "is_root": False, "parents": [271], "properties": [
        ("type", str, ["Controller", "Headset", "Keyboard", "Mouse", "VR Headset", "Memory Card", "Other"]),
        ("platform", str, ["PlayStation", "Xbox", "Nintendo Switch", "PC", "Other"]),
        ("brand", str),
        ("model", str),
        ("wireless", bool),
    ]},

    {"id": 274, "name": "Musical Instruments", "is_root": False, "parents": [6, 8], "properties": [
        ("instrument_type", str, ["String", "Wind", "Percussion", "Electronic", "Keyboard", "Other"]),
        ("brand", str),
        ("model", str),
        ("material", str),
        ("skill_level", str, ["Beginner", "Intermediate", "Professional"]),
        ("acoustic_or_electric", str, ["Acoustic", "Electric", "Acoustic-Electric"]),
    ]},

    {"id": 275, "name": "String Instruments", "is_root": False, "parents": [274], "properties": [
        ("instrument", str, ["Guitar", "Violin", "Viola", "Cello", "Double Bass", "Harp", "Banjo", "Mandolin", "Ukulele", "Other"]),
        ("brand", str),
        ("model", str),
        ("number_of_strings", int),
        ("acoustic_or_electric", str, ["Acoustic", "Electric", "Acoustic-Electric"]),
        ("handedness", str, ["Right", "Left"]),
        ("skill_level", str, ["Beginner", "Intermediate", "Professional"]),
        ("material", str),
    ]},

    {"id": 276, "name": "Wind Instruments", "is_root": False, "parents": [274], "properties": [
        ("instrument", str, ["Flute", "Clarinet", "Saxophone", "Trumpet", "Trombone", "Tuba", "Oboe", "Bassoon", "Harmonica", "Other"]),
        ("brand", str),
        ("model", str),
        ("material", str),
        ("skill_level", str, ["Beginner", "Intermediate", "Professional"]),
    ]},

    {"id": 277, "name": "Percussion Instruments", "is_root": False, "parents": [274], "properties": [
        ("instrument", str, ["Drum Set", "Snare Drum", "Bass Drum", "Cymbals", "Xylophone", "Tambourine", "Triangle", "Other"]),
        ("brand", str),
        ("model", str),
        ("material", str),
        ("skill_level", str, ["Beginner", "Intermediate", "Professional"]),
    ]},

    {"id": 278, "name": "Electronic Instruments", "is_root": False, "parents": [274], "properties": [
        ("instrument", str, ["Keyboard", "Synthesizer", "Electric Guitar", "Electric Bass", "Electronic Drum Set", "MIDI Controller", "Sampler", "Other"]),
        ("brand", str),
        ("model", str),
        ("number_of_keys", int),
        ("number_of_strings", int),
        ("skill_level", str, ["Beginner", "Intermediate", "Professional"]),
    ]},

    {"id": 279, "name": "Collectibles", "is_root": False, "parents": [6], "properties": [
        ("collectible_type", str, ["Trading Card", "Memorabilia", "Limited Edition", "Figurine", "Stamp", "Coin", "Other"]),
        ("brand", str),
        ("series", str),
        ("year", int),
        ("limited_edition_number", int),
        ("autographed", bool),
    ]},

    {"id": 280, "name": "Trading Cards", "is_root": False, "parents": [279], "properties": [
        ("card_game", str, ["Pokemon", "Magic: The Gathering", "Yu-Gi-Oh!", "Sports", "Other"]),
        ("player_or_character", str),
        ("card_number", str),
        ("rarity", str, ["Common", "Uncommon", "Rare", "Ultra Rare", "Secret Rare", "Other"]),
        ("set", str),
        ("year", int),
        ("autographed", bool),
        ("graded", bool),
        ("grade", str),
    ]},

    {"id": 281, "name": "Memorabilia", "is_root": False, "parents": [279], "properties": [
        ("type", str, ["Autograph", "Poster", "Photo", "Jersey", "Prop", "Other"]),
        ("subject", str),
        ("year", int),
        ("autographed", bool),
        ("authenticated", bool),
        ("authentication_service", str),
    ]},

    {"id": 282, "name": "Limited Editions", "is_root": False, "parents": [279], "properties": [
        ("item_type", str, ["Book", "Movie", "Music", "Game", "Figurine", "Print", "Other"]),
        ("title", str),
        ("artist_or_author", str),
        ("edition_size", int),
        ("numbered", bool),
        ("number", int),
        ("year", int),
        ("certificate_of_authenticity", bool),
    ]},

    {"id": 283, "name": "Other Media", "is_root": False, "parents": [6], "properties": [
        ("media_type", str, ["Audio Book", "Podcast", "Magazine", "Newspaper", "Sheet Music", "Other"]),
        ("title", str),
        ("author_or_artist", str),
        ("release_date", str),
        ("format", str),
        ("language", str),
        ("publisher", str),
    ]},

]